import time
import requests
print("starting screensaver on projector")
def posttext(text):
    requests.get("http://10.0.0.14:1998/postsign?text=" + text)
def screensaver():
    requests.get("http://10.0.0.14:1998/postsign?text=screen")
    time.sleep(3)
    requests.get("http://10.0.0.14:1998/postsign?text=saver")
    time.sleep(3)
    requests.get("http://10.0.0.14:1998/postsign?text=screensaver")
    time.sleep(3)
    requests.get("http://10.0.0.14:1998/postsign?text=s")
    time.sleep(0.1)
    requests.get("http://10.0.0.14:1998/postsign?text=sc")
    time.sleep(0.1)
    posttext("scr")
    time.sleep(0.1)
    posttext("scre")
    time.sleep(0.1)
    posttext("scree")
    time.sleep(0.1)
    posttext("screen")
    time.sleep(0.1)
    posttext("screens")
    time.sleep(0.1)
    posttext("screensave")
    time.sleep(0.1)
    posttext("screensaver")
    time.sleep(0.1)
    posttext("screensaver")
    time.sleep(0.1)
    posttext("screensaver")
    time.sleep(5)
    screensaver()
screensaver()